version: '3.7'
services:
  sqlserver_db_container:
    image: my_sqlserver_image
    build: ./my_sqlserver
    container_name: sqlserver-container
    environment:
        SA_PASSWORD: yourStrong(!)Password
        ACCEPT_EULA: Y
    volumes:
       - sqlserver_db_data_container:/var/opt/mssql
    ports:
      - 1433:1433
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "yourStrong(!)Password" -Q "SELECT 1" -b -o /dev/null
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s      
volumes:
  sqlserver_db_data_container:
