version: '3.7'
services:
  sqlserver_db_container:
    image: mcr.microsoft.com/mssql/server:2019-latest
    build: ./my_sqlserver
    container_name: sqlserver-container
    environment:
        SA_PASSWORD: yourStrong(!)Password
        ACCEPT_EULA: Y
    volumes:
       - sqlserver_db_data_container:/var/opt/mssql
    ports:
      - 1433:1433
     
volumes:
  sqlserver_db_data_container:
